package rules;
dialect  "mvel"
import com.huawei.hicloud.model.ValuationFact;
import javafx.beans.binding.When;


rule "valuation"
    when
        $fact : ValuationFact(price > 100)
    then
        $fact.setPrice((int) ($fact.getPrice() * 0.8));
        System.out.println("Rule valuation execute end!");
    end


rule "valuation2"
    when
        $fact : ValuationFact(price > 100)
    then
        $fact.setPrice((int) ($fact.getPrice() * 0.8));
        System.out.println("Rule valuation execute end!");
    end
