package rules;
dialect  "mvel"
import com.huawei.hicloud.model.ValuationFact;
import javafx.beans.binding.When;

global java.lang.Integer $price


rule "valuation"
    when
        $fact: ValuationFact(price > 100)
    then
        $fact.setPrice((int) ($fact.getPrice() * 0.8));
        $price = $fact.getPrice();
        System.out.println("Rule valuation execute end! price = " + $price);
    end


rule "valuation2"
    when
        $fact : ValuationFact(price > 100)
    then
        $fact.setPrice((int) ($fact.getPrice() * 0.8));
        System.out.println("Rule valuation2 execute end! price = " + $price);
    end
